# Generated by Django 3.2.7 on 2021-09-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TR', 'Transport'), ('ET', 'Entertainment'), ('PH', 'Health'), ('CT', 'Clothes'), ('FD', 'Food'), ('AD', 'Accommodation'), ('OT', 'Others')], default='OT', max_length=2)),
                ('sum_value', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.category')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('netto_budget', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('expence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.expence')),
            ],
        ),
    ]
