# Generated by Django 3.2.7 on 2021-09-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='netto_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='tax',
        ),
    ]
