# Generated by Django 3.2.7 on 2021-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_budget_expence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sum_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000),
        ),
    ]
