# Generated by Django 3.2.7 on 2021-09-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_category_sum_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='category',
        ),
    ]
