# Generated by Django 3.2.7 on 2021-09-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_expence_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
