# Generated by Django 3.2.7 on 2021-09-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_expence_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.profile'),
        ),
    ]
