# Generated by Django 3.2.7 on 2021-09-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20210926_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.profile'),
        ),
    ]
