# Generated by Django 3.2.7 on 2021-09-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_budget_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.budget'),
        ),
    ]
