# Generated by Django 3.2.7 on 2021-10-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20210929_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.budget'),
        ),
    ]
