# Generated by Django 3.2.7 on 2021-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_auto_20211002_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_money',
            field=models.DecimalField(decimal_places=2, max_digits=1000000, null=True),
        ),
    ]
