# Generated by Django 3.2.7 on 2021-10-03 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_alter_expence_expense_monthly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='expense_monthly_date',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
