# Generated by Django 3.2.7 on 2021-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_alter_expence_expense_monthly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
