# Generated by Django 3.2.7 on 2021-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_expence_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
