# Generated by Django 3.2.7 on 2021-10-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_alter_expence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
